package org.learning.model;

public enum HabitableBuildingTypes {
    CASTLE, HOTEL, SINGLEFAMILYHOUSE, VILLA, PALACE, COTTAGE, HOUSEBOAT, RESIDENCE, FORT, MULTIFAMILYHOUSE, UNDERGROUNDHOUSE, MANSION, TINYHOME, MOBILEHOME, BUNGALOW
}